version: "3.4"  # optional since v1.27.0
volumes:
  chain:

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "127.0.0.1:5432:5432"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: "${DB_USER}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - "127.0.0.1:3306:3306"
  substrate:
    image: sora2/substrate:1.0.0
    ports:
      - "127.0.0.1:9933:9933"
      - "127.0.0.1:9944:9944"
    volumes:
      - chain:/chain
    command: --name sora2-node --chain main --base-path /chain --unsafe-ws-external --unsafe-rpc-external --execution Wasm --pruning archive --rpc-cors all
    healthcheck:
      test: >-
        curl -H 'Content-Type: application/json' -d '{"id": 1, "jsonrpc": "2.0", "method": "system_health", "params": []}' 127.0.0.1:9933 | grep -E 'result'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 300s
  import:
    build: .
    scale: 0
    depends_on:
      postgres:
        condition: service_started
      substrate:
        condition: service_healthy
    command: "env SUBSTRATE_URL=ws://substrate:9944 DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres/${DB_NAME} python run_node_processing.py -f"
  web:
    build: .
    depends_on:
      - "postgres"
    ports:
      - "80:8888"
    command: "env DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres/${DB_NAME} python webapp.py"
